### ISSUE TITLE
cannot import name 'fitimage' from 'kivymd.utils'

### ISSUE THREAD

**Issue by viktor02** [Alb-310/Geogramint#1]
```
(venv) PS C:\Users\x\Documents\steamvr\Geogramint> python geogramint.py
[WARNING] [Config      ] Older configuration version detected (0 instead of 24)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in C:\Users\x\.kivy\logs\kivy_22-08-26_0.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.2
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.4.5
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "C:\Users\x\Documents\steamvr\Geogramint\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\x\Documents\steamvr\Geogramint\venv\Scripts\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [KivyMD      ] 1.0.2, git-38fe356, 2022-08-11 (installed at "C:\Users\x\Documents\steamvr\Geogramint\venv\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 516.94'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1080/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "C:\Users\x\Documents\steamvr\Geogramint\geogramint.py", line 23, in <module>
     from utils import resultDisplay
   File "C:\Users\x\Documents\steamvr\Geogramint\utils\resultDisplay.py", line 6, in <module>
     from kivymd.utils import fitimage
 ImportError: cannot import name 'fitimage' from 'kivymd.utils' (C:\Users\x\Documents\steamvr\Geogramint\venv\lib\site-packages\kivymd\utils\__init__.py)
```
Python 3.10.5, Windows 10
Git version

**Comment by Alb-310** [comment]
Thx for reporting the error. As said in the wiki and README, I would like to remind that the tool is only compatible with python 3.8 and 3.9 since Kivy is not working well with the 3.10.

For this error, I'm aware of it since this morning, it will be fixed during the next 48h (hopefully).

**Comment by Alb-310** [comment]
It's fixed @viktor02 !

The update of Kivymd caused some minor altercations on the UI
